In [21]:
from operator import index

import pandas as pd
import time

In [22]:

start_time_overall = time.time()
elapsed_times_list = []

#1 loading csv file

In [23]:
start_time1 = time.time()

df = pd.read_csv("beer_reviews.csv")

end_time1 = time.time()
elapsed_time1 = end_time1 - start_time1
elapsed_times_list.append(elapsed_time1)
print(f"Elapsed time: {elapsed_time1} seconds")

Elapsed time: 1.6810290813446045 seconds

#2 which beer style is rated highest review overall

In [24]:
start_time2 = time.time()

highest_review = df[df['review_overall'] == 5]

end_time2 = time.time()
elapsed_time2 = end_time2 - start_time2
elapsed_times_list.append(elapsed_time2)
print(f"Elapsed time: {elapsed_time2} seconds")

highest_review

Elapsed time: 0.014121532440185547 seconds

,index,brewery_id,brewery_name,review_time,review_overall,review_aroma,review_appearance,review_profilename,beer_style,review_palate,review_taste,beer_name,beer_abv,beer_beerid
11,11,1075,Caldera Brewing Company,1283154365,5.0,5.0,4.0,MadeInOregon,Herbed / Spiced Beer,4.0,4.0,Caldera Ginger Beer,4.7,52159
25,25,1075,Caldera Brewing Company,1318802642,5.0,5.0,3.5,optimator13,Rauchbier,3.5,5.0,Rauch Ür Bock,7.4,58046
31,31,1075,Caldera Brewing Company,1315014054,5.0,4.5,4.0,Bung,Rauchbier,4.0,5.0,Rauch Ür Bock,7.4,58046
42,42,1075,Caldera Brewing Company,1305926255,5.0,4.5,3.5,Deuane,Rauchbier,4.0,5.0,Rauch Ür Bock,7.4,58046
73,73,1075,Caldera Brewing Company,1246913078,5.0,4.0,4.5,GratefulBeerGuy,American Pale Ale (APA),4.5,4.0,Caldera Pale Ale,5.5,25414
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1463015,1586605,14359,The Defiant Brewing Company,1163291143,5.0,5.0,5.0,NyackNicky,Pumpkin Ale,5.0,5.0,The Horseman's Ale,5.2,33061
1463016,1586606,14359,The Defiant Brewing Company,1162871808,5.0,4.5,4.0,blitheringidiot,Pumpkin Ale,5.0,5.0,The Horseman's Ale,5.2,33061
1463017,1586607,14359,The Defiant Brewing Company,1162865640,5.0,5.0,4.5,PopeDX,Pumpkin Ale,5.0,4.5,The Horseman's Ale,5.2,33061
1463019,1586609,14359,The Defiant Brewing Company,1162684892,5.0,4.0,3.5,maddogruss,Pumpkin Ale,4.0,4.0,The Horseman's Ale,5.2,33061
1463023,1586613,14359,The Defiant Brewing Company,1160005319,5.0,4.5,4.5,cbl2,Pumpkin Ale,4.5,4.5,The Horseman's Ale,5.2,33061

#3 Best beer per brewery

In [25]:
start_time3 = time.time()

best_beer_per_brewery = df.sort_values(by=["review_overall", 'index'],ascending=False).groupby("brewery_name").head(1)

end_time3 = time.time()
elapsed_time3 = end_time3 - start_time3
elapsed_times_list.append(elapsed_time3)
print(f"Elapsed time: {elapsed_time3} seconds")

best_beer_per_brewery[best_beer_per_brewery['brewery_name'] == 'Pacific Coast Brewing Company']

Elapsed time: 0.4649784564971924 seconds

,index,brewery_id,brewery_name,review_time,review_overall,review_aroma,review_appearance,review_profilename,beer_style,review_palate,review_taste,beer_name,beer_abv,beer_beerid
951,958,2724,Pacific Coast Brewing Company,1200257612,4.5,4.5,3.5,MisterClean,American Stout,4.5,5.0,Killer Whale Stout,5.0,8770

#4 Average review_overall Score per Brewery and Identify the Top 5 Breweries

In [26]:
start_time4 = time.time()

average_reviews_per_brewery = df.groupby('brewery_name')['review_overall'].mean().reset_index()
average_reviews_per_brewery.columns = ['brewery_name', 'avg_review_overall']

end_time4 = time.time()
elapsed_time4 = end_time4 - start_time4
elapsed_times_list.append(elapsed_time4)
print(f"Elapsed time: {elapsed_time4} seconds")

average_reviews_per_brewery

Elapsed time: 0.10434293746948242 seconds

                 brewery_name  avg_review_overall
0           't Hofbrouwerijke            3.702703
1       (512) Brewing Company            4.076014
2       10 Barrel Brewing Co.            3.743590
3        1516 Brewing Company            4.100000
4     16 Mile Brewing Company            3.570652
...                       ...                 ...
5001       Ölvisholt Brugghús            3.912371
5002            Öufi Brauerei            3.500000
5003              Ølfabrikken            4.069966
5004           Ørbæk Bryggeri            3.583333
5005     Łódzkie Browary S.A.            3.500000

[5006 rows x 2 columns]

#5 most reviewed beer styles

In [27]:
start_time5 = time.time()

most_reviewed_styles = df.groupby('beer_style').size().reset_index(name='review_count')
most_reviewed_styles = most_reviewed_styles.sort_values(by='review_count', ascending=False)

end_time5 = time.time()
elapsed_time5 = end_time5 - start_time5
elapsed_times_list.append(elapsed_time5)
print(f"Elapsed time: {elapsed_time5} seconds")

most_reviewed_styles

Elapsed time: 0.08071303367614746 seconds

                          beer_style  review_count
12                      American IPA        107913
9     American Double / Imperial IPA         81143
14           American Pale Ale (APA)         56871
89            Russian Imperial Stout         50997
11  American Double / Imperial Stout         48299
..                               ...           ...
56                              Faro           608
48             English Pale Mild Ale           460
88                        Roggenbier           395
72                             Kvass           229
64                          Happoshu           120

[104 rows x 2 columns]

#6 Identify the Most Polarizing Beers Based on review_aroma

In [28]:
start_time6 = time.time()

variance_aroma_by_beer = df.groupby('beer_style')['review_aroma'].var().reset_index()
variance_aroma_by_beer.columns = ['beer_style', 'review_aroma']

end_time6 = time.time()
elapsed_time6 = end_time6 - start_time6
elapsed_times_list.append(elapsed_time6)
print(f"Elapsed time: {elapsed_time6} seconds")

variance_aroma_by_beer

Elapsed time: 0.08501338958740234 seconds

                     beer_style  review_aroma
0                       Altbier      0.337345
1        American Adjunct Lager      0.515742
2      American Amber / Red Ale      0.381898
3    American Amber / Red Lager      0.421482
4           American Barleywine      0.274325
..                          ...           ...
99                 Vienna Lager      0.348891
100                  Weizenbock      0.266336
101                   Wheatwine      0.289919
102               Winter Warmer      0.357123
103                     Witbier      0.380176

[104 rows x 2 columns]

In [29]:
end_time_overall = time.time()
elapsed_time_visualisation = end_time_overall - start_time_overall
elapsed_time_no_visualisation = sum(elapsed_times_list)
print(f"Elapsed time: {elapsed_time_no_visualisation} seconds without visualising data")
print(f"Elapsed time: {elapsed_time_visualisation} seconds with visualising data")

Elapsed time: 2.4301984310150146 seconds without visualising data
Elapsed time: 2.89383602142334 seconds with visualising data